<?php
/** @var Cadence\Fbpixel\Block\AbstractBlock $block */
$helper = $block->getHelper();
if (!$helper->isVisitorPixelEnabled()) {
	return;
}
$id = $helper->getVisitorPixelId();


$allowServices = false;
if ((int)$block->isCookieRestrictionModeEnabled()):
	$cookie_value = $block->getCookieValue($block->getCookieName());

	if (!empty($cookie_value)):
		$allowed = json_decode($cookie_value, true);

		if ($allowed[(int)$block->getCurrentWebsiteId()] === 1) {
			$allowServices = true;
		}
	endif;

else:
	$allowServices = false;
endif;

if (!$allowServices):
	return;
endif;
?>
<!-- Facebook Pixel Code -->
<script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '<?php echo $id ?>');
    fbq('track', "PageView");
</script>
<noscript><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=<?php echo $id ?>&ev=PageView&noscript=1"
    /></noscript>

